In [43]:
import numpy as np

In [44]:
input_vector = np.array([1,2,3,4,5,6])
N = 5
inc_false = np.vander(input_vector, N, increasing = False)
inc_true = np.vander(input_vector, N, increasing = True)

print("Decreasing order of vander matrix when increasing is False:\n\n", inc_false)
print('-'* 60)
print("Increasing order of vander matrix when increasing is True:\n\n", inc_true)

Decreasing order of vander matrix when increasing is False:

 [[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]
------------------------------------------------------------
Increasing order of vander matrix when increasing is True:

 [[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]


In [45]:
my_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3

def moving_average(my_list, k):
    cumsum = [0]
    moving_avg = []
    for i, x in enumerate(my_list, 1):
        cumsum.append(cumsum[i-1] + x)
        if i >= k:
            moving_ave_func =  round(((cumsum[i] - cumsum[i-k])/k), 2)
            moving_avg.append(moving_ave_func)
    print(moving_avg)
    print(len(moving_avg))
moving_average(my_list, k)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
11
